#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -location 1 -xoffset 10 -yoffset 32 -line-padding 8 -columns 1 -width 40 -lines 10 -padding 50 -hide-scrollbar -show-icons -drun-icon-theme "Papirus"
